version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "MalikHw"
    labels:
      - "dependencies"
      - "python"
    groups:
      pyqt:
        patterns:
          - "PyQt6*"
        update-types:
          - "minor"
          - "patch"
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    ignore:
      - dependency-name: "PyQt6"
        update-types: ["version-update:semver-major"]
      - dependency-name: "PyQt6-Charts"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "MalikHw"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
